[package]
name = "rswodlib-tokio-worker-map"
edition.workspace = true
description = "Map values through asynchronous worker tasks"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-channel = "2.3.1"
futures-util = { version = "0.3.29", default-features = false, features = ["std"] }
tokio = { version = "1.29.0", features = ["rt", "sync"] }

[dev-dependencies]
tokio = { version = "1.29.0", features = ["macros"] }

[lints]
workspace = true
