[package]
name = "rswodlib-tokio-buffered-tasks"
edition.workspace = true
#description = ...
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
futures-util.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }

[lints]
workspace = true
